### PR TITLE
Bike fix

### PR DESCRIPTION
**Pull request by Coolthulhu**
Again: only the last commit matters here.

Works like this:
* Scales energy use with proportion of energy used
* At max use, it's 500% of base energy usage
* Removes the `power *= str_cur`, since it wasn't properly accounted for and was a bad idea anyway (strength doesn't "start" at 0, 0 is just the low cap)

### CODE REVIEW

**Comment by mugling** [comment]
Can you rebase 86898d9 out of this and I'll merge just 5d44684

**Comment by mugling** [comment]
Actually can you just merge the original PR and then submit this as a new one. This needs further work:
- division by zero if `power` is zero (consider check in `item_factory` plus `assert` here)
- `STR` should affect maximum speed for `MANUAL_ENGINE`
- JSON values for foot crank and hand rims need updating

**Comment by Coolthulhu** [comment]
Rebased.
Not sure why does the diff show everything, including your branch.

**Comment by mugling** [comment]
No I'm not sure either. I tried merging my branch against master but it didn't get rid of the huge delta. I don't want to stuff it all up so can you merge the parent as this is the only outstanding problem. The idea behind your bike changes is sound and can get merged afterwards once we resolve the above.

**Comment by Firestorm01X2** [comment]
@mugling Hello.
I know you left long time ago, but I think it would be good idea to inform you that currently https://github.com/cataclysmbnteam/Cataclysm-BN is up. 
It is fork of CDDA that tries to fix a lot of problems in CDDA and it is leading by Coolthulhu.
You might be interested.

**Pull request merged**
