### PR TITLE
Hack in traction velocity limits

### PR DESCRIPTION
**Pull request by Coolthulhu**
My branch is based on current master, while yours is based on some older master. I don't know how to skip all those commits in between.

The last commit is the one that matters here.

### CODE REVIEW

**Comment by mugling** [comment]
The last two commits of my PR implement the same but via slightly simpler code. I'm not sure if there is an advantage to either?

**Comment by Coolthulhu** [comment]
I only see you handle the skidding part, but not the (more important) traction part.

**Comment by mugling** [comment]
True, but why do you want to slow down on poor traction? Have you ever driven a vehicle across a muddy field - the lack of traction keeps you moving for longer.

What you're getting at wants to be implemented in `vehicle::acceleration`

**Comment by Coolthulhu** [comment]
I'm trying to add a minimal set of changes to make the PR mergeable.
If you have a better solution, push it to your branch and I'll see if it does everything that is required.

My PR here solves the problem of vehicles retaining full velocity when going offroading, which is a major problem.

**Comment by mugling** [comment]
They should retain more velocity off road. If you were doing 200mph on the road driving on to a field won't suddenly brake you to 30mph.

What should happen is it's harder to accelerate off-road thereby limiting top speed. This is already implemented in `vehicle::thrust`. The missing part is that some engines should be better off-road than others but this isn't a regression.

**Comment by mugling** [comment]
They should retain more velocity off road. If you were doing 200mph on the road driving on to a field won't suddenly brake you to 30mph. The previous implementation is both incorrect from a physics POV and also gameplay (traveling at 200mph then steering on to grass to brake)

What should happen is it's harder to accelerate off-road thereby limiting top speed. This was already implemented in vehicle::thrust and is preserved. The missing part is that some engines should be better off-road than others but this isn't a regression. Once we have that we can look into different tyre properties and finally have dune buggies and thelike.

**Comment by Coolthulhu** [comment]
> If you were doing 200mph on the road driving on to a field won't suddenly brake you to 30mph.

Suddenly or not, it is unaccepable to allow indefinitely retaining road top velocity when offroading.

**Comment by mugling** [comment]
Have implemented this fix in the parent branch including a new commit that results in a proportional slowdown when moving to offroad terrain.

**Pull request closed without merging**
